### ISSUE TITLE
why are you sending me spam emails???

### ISSUE THREAD

**Issue by amishshah** [Jonyk56/RANGEJS#1]
![screenshot_20190304-171103](https://user-images.githubusercontent.com/10330923/53750073-c3ab8c80-3ea0-11e9-8c1b-f02ffb28d38e.jpg)
I don't really appreciate this spam from your dumb useless repo

**Comment by RuyiLi** [comment]
charge your phone

**Comment by amishshah** [comment]
receiving such a nonsensical email is what drained it so fast

**Comment by RuyiLi** [comment]
just use RANGEJS to charge it

**Comment by amishshah** [comment]
ah yes of course

**Comment by CoderSudaWuda** [comment]
Node.js is shutting down? Welp, I'm going to pnpm now.

**Comment by Jonyk56** [comment]
Not spam

**Comment by Jonyk56** [comment]
Just suggesting
